name: Compile LaTeX Resume

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.tex'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.tex'

permissions:
  contents: write

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex
        args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
        
    - name: Move PDF to root
      run: mv resume.pdf ./resume.pdf
        
    - name: Commit and push PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add resume.pdf
        git diff --staged --quiet || git commit -m "Auto-compile resume.pdf"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
